version: '2'
services:
  # Rabbit is our main message queue
  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    ports:
      - 5672:5672
      - 15672:15672

  # Redis is where we store results (for now)
  redis:
    image: redis:2.8.19
    hostname: redis
    ports:
      - 6379:6379

  # Celery beat
  scheduler:
    image: collins
    build: .
    entrypoint: /code/start_scheduler.sh
    command: celery -A tasks worker --loglevel=info
    environment:
      - RABBITMQ_URL=pyamqp://guest:guest@rabbit//
    links:
      - rabbit
    volumes:
      - ./:/code
    depends_on:
      - rabbit
  # Django based api/admin site
  api:
    image: collins
    build: .
    command: /code/start_api.sh
    environment:
      - RABBITMQ_URL=pyamqp://guest:guest@rabbit//
    links:
      - rabbit
    ports:
      - 8000:8000
    volumes:
      - ./:/code
    depends_on:
      - rabbit

  # flower
  monitor:
    image: collins-monitor
    build: ./monitor
    environment:
      - RABBITMQ_URL=pyamqp://guest:guest@rabbit//
    build: ./monitor
    links:
      - rabbit
    ports:
      - 5555:5555
    depends_on:
      - rabbit


  # remote client
  site_1:
    image: collins-worker
    build: ./client/
    environment:
      - REDIS_URL=redis://redis
      - SITE_NAME=SITE_1
      - RABBITMQ_URL=pyamqp://guest:guest@rabbit//
      - RESULTS_API=http://api:8000/api/v1/results/
    links:
      - rabbit
      - redis
      - api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - rabbit
      - redis

  # remote client
  site_2:
    image: collins-worker
    build: ./client/
    environment:
      - REDIS_URL=redis://redis
      - SITE_NAME=SITE_2
      - RABBITMQ_URL=pyamqp://guest:guest@rabbit//
      - RESULTS_API=http://api:8000/api/v1/results/
    links:
      - rabbit
      - redis
      - api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - rabbit
      - redis
